[package]
name = "packer"
version = "0.1.0"
edition = "2021"

[dependencies]

[lib]
name = "packer"
path = "src/lib.rs"
crate-type = ["rlib"]


[profile.release]
strip = true
opt-level = 3
lto = true
codegen-units = 1
